_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": darwin-arm64
batch_size:
    value: 512
clip_range:
    value: 0.22
gae_lambda:
    value: 0.95
gamma:
    value: 0.98
learning_rate:
    value: 0.000634
n_epochs:
    value: 23
n_steps:
    value: 2048
train_timesteps:
    value: 500000
